### ISSUE TITLE
Transcoding failed if data track in source file

### ISSUE THREAD

**Issue by narcotix88** [elonen/clapshot#28]
Thank you for your amazing work. 
I'm currently considering using Clapshot in my workflow, and I found a bug.
When adding a ".mov" file directly from our NLE (Davinci Resolve) the file contains a data track with metadata, we get a "transcoding failed" when adding it to Clapshot.
The problem is that "- maps 0" copy all stream including the data track, but mp4 container do not support data track.

You should consider using "-dn" argument to delete this track from the mp4 file.

For example line 107 in video_compressor.rs

```rust
cmd = cmd.args(&[
                "-nostats",
                "-vcodec", "libx264",
                "-vf", &format!("scale={}:{}", 1920, -8),
                "-map", "0",  // copy all streams
                "-preset", "faster", "-dn", //remove data stream
                "-acodec", "aac",
                "-ac", "2",
                "-strict", "experimental",
                "-b:v", &format!("{}", args.video_bitrate),
                "-b:a", &format!("{}", 128000),
            ]).arg(&dst);
``` 
This file for example contains a data track.
https://transfer.zadafrik.com/download/a1290555c4d64f3a/#ElMgPFZiyaZu5mfvEKknsQ

**Comment by elonen** [comment]
Thank you for a good, reproducible bug report @narcotix88 !
