### ISSUE TITLE
Auto pause when typing (Auto play when sending)

### ISSUE THREAD

**Issue by narcotix88** [elonen/clapshot#29]
It would be cool to auto pause video when typing a comment and autoplay when sending it, to "live comment" the video.

I already implemented a switch for that in the client, I can send you the code if you want.

**Comment by elonen** [comment]
Sounds like a good idea, as long as the autostart only happens if it was paused during playback.

If you want to send a PR, do it against `dev` branch, as it differs significantly from the current master. If not, I'll probably implement this for the next release.
