### ISSUE TITLE
Connecting Server...

### ISSUE THREAD

**Issue by bobbyrabbit** [elonen/clapshot#30]
I am trying to connect using http://ServerIP:8080 but continuing to get Connecting Server..

I used following command to setup docker container:
```
docker run --rm -it -p 0.0.0.0:8080:80 -v clapshot-demo:/mnt/clapshot-data/data \
  elonen/clapshot:latest-demo-htadmin
```
Any help would be appreciated

**Comment by elonen** [comment]
Since it's still connecting to the default 127.0.0.1, your Docker image is probably not the new one.
You may need to refresh you Docker cache, or explicitly specify `elonen/clapshot:0.5.5_20230425-demo-htadmin`

When you run the correct one, log should look like this:

```
$ docker run -e CLAPSHOT_URL_BASE='192.168.1.12:8080/' --rm -it -p 0.0.0.0:8080:80 -v clapshot-demo:/mnt/clapshot-data/data elonen/clapshot:latest-demo-htadmin


==============================================
     _____ _                 _           _
    / ____| |               | |         | |
   | |    | | __ _ _ __  ___| |__   ___ | |_
   | |    | |/ _` | '_ \/ __| '_ \ / _ \| __|
   | |____| | (_| | |_) \__ | | | | (_) | |_
    \_____|_|\__,_| .__/|___|_| |_|\___/ \__|
                  | |
                  |_|

---  Browse http://192.168.1.12:8080/         for Clapshot
---  or     http://192.168.1.12:8080/htadmin  for user management
---
---  Default users:
---   - admin:admin     (can edit other people's videos)
---   - demo:demo
---   - alice:alice123
---
---  User management admin:
---   - htadmin:admin   (only for /htadmin)
==============================================================
```

(Note that the ascii graphics now only say only "Clapshot", not "Running Clapshot" as before.)

**Comment by elonen** [comment]
(You might also need to force-reload the browser page with `ctrl/cmd-R` in case yourt browser was caching the old client/config.)
