### ISSUE TITLE
Video timeline jumps from 00:30:00:00 to 01:30:00:00

### ISSUE THREAD

**Issue by azazel75** [elonen/clapshot#36]
Hello and tanks for your nice project!
For the first time we added a video longer than 30 minutes and we stumbled upon what we think is a bug.  When the timeline of the video goes beyond 30 minutes, it jumps directly to 1:30:00, it goes on adding 1h and then when it reaches what would be  a real 1h it resets back to from 01:59:59 to 01:00:00.It repeats that when it reaches 01:30:00, so jumping to 02:30:00 and so on.

You can see an excerpt from the timeline animation here: 
![clapshot-timeline-counter-issue.gif](https://i.postimg.cc/FH7NBvTT/clapshot-timeline-counter-issue.gif)

cc @diego-calza, @lelit

**Comment by azazel75** [comment]
We upgraded to the image tagged `0.5.5_20230425-demo-htadmin` if that would solve the issue... but we had no luck

**Comment by elonen** [comment]
Great catch, thank you!
