### ISSUE TITLE
Debian 12 required?

### ISSUE THREAD

**Issue by Stooovie** [elonen/clapshot#44]
Hi, after creating, installing the debs and running `clapshot-server`, I get this:

```
root@clapshot:~/clapshot# clapshot-server
clapshot-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clapshot-server)
clapshot-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by clapshot-server)
clapshot-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by clapshot-server)
```
`sudo apt -y install libc6 ` returns `libc6 is already installed at the requested version (2.31-13+deb11u7)`, nothing newer is available. 

Is Debian 12 required? I'm on Debian 11. Or any other tips? Thanks!

**Comment by elonen** [comment]
I'm hosting it on a Bullseye, so at least not the previous release.
Then again, I recently had to start building separate deb11 and deb12 versions for https://github.com/elonen/ldap_authz_proxy/releases, so it's possible something's changed recently.
I'll have a look and see if I could port the multi-debian build scripts to Clapshot server as well.

**Comment by Stooovie** [comment]
I have upgraded the LXC to Bookworm in the meantime and the error is gone. This very issue is solved for me. I have others :) But slowly working my way to a working Clapshot system. Thank you so much for your work!

**Comment by elonen** [comment]
Note: Simply changing `bookworm` to `bullseye` in Dockerfile.server seems to compile clapshot-server_*.deb on Debian 11 just fine:
```
sed -i '' 's/bookworm/bullseye/g' Dockerfile.server
make debian-docker
ls server/dist_deb
```
