### ISSUE TITLE
How to run behind Nginx Proxy Manager?

### ISSUE THREAD

**Issue by Stooovie** [elonen/clapshot#46]
I use NPM as a reverse proxy but when I put Clapshot behind it, all I get is "Connecting server". I run the server like this (and took me a while to discover that the -e baseurl parameter can not be at the end of the command):

`docker run --rm -it -p 0.0.0.0:8080:80 -v clapshot-demo:/mnt/clapshot-data/data -e CLAPSHOT_URL_BASE=192.168.0.152:8080/  elonen/clapshot:latest-demo-htadmin`

and am able to access it via http://192.168.0.152:8080 from browser running on a different computer, but not via a subdomain (clapshot.MYDOMAIN.com) - again, it does seem to connect to the server but I only get endless "Connecting server".

NPM is configured like this:
![Screenshot 2023-12-13 at 12 16 34](https://github.com/elonen/clapshot/assets/10572373/a48e9788-f627-4172-aa15-0932bdb9f75a)
![Screenshot 2023-12-13 at 12 16 42](https://github.com/elonen/clapshot/assets/10572373/72163841-5455-419b-bd7f-6298aff3a653)

Thanks for any tips!

**Comment by elonen** [comment]
Closing this as in favor of discussion #45
