### ISSUE TITLE
Include subtitles for visualization and correction

### ISSUE THREAD

**Issue by Manuel5cc** [elonen/clapshot#51]
Adding the ability to display either embedded subtitles or external .srt files to include in the reviews, since this is a common step in video production these days.

**Comment by elonen** [comment]
Showing an SRT wouldn't technically be very difficult.

The bigger question is, how the UI/UX should support this feature.
For example, how would you attach an SRT to a video, should there be multiple ones and if so, how to switch between them; would you have to change font/size/color, how should commenting and annotation drawings interact with the texts etc etc.

Do you have ideas / opinions on these?

**Comment by Manuel5cc** [comment]
I think for the visualization it should be enough to render the subtitles in white with a black shadow or background to ensure visibility in all situations. 
As for the UI, probably it's not necessary to support several subtitles with one same video, as normally you'd need to have separate videos for every language (to adapt lower thirds, etc.) and it's also usually reviewed by different people. A simple on/off switch should do it. The review process itself can be comment-time based as well.
The identification is normally based in the filename, video players recognize the language following this scheme:
```
name.of.the.video.mp4
name.of.the.video.en.srt
name.ofthe.video.es.srt
```

**Comment by elonen** [comment]
Subtitles implemented in `master`.
