### ISSUE TITLE
"internal error. Unable to create upload dirue is:closed"

### ISSUE THREAD

**Issue by afill86** [elonen/clapshot#81]
Suddenly, video files stopped uploading. It says “internal error. Unable to create upload dirue is:closed” Can anyone tell me what's wrong?

**Comment by elonen** [comment]
A bit more context would be useful (e.g. how was Clapshot installed, where exactly did that error appear, and what else was around it) but "Unable to create upload dir" sounds like disk space running out or other such file system issue on the host you are running the server on.
